# Generated by Django 3.0.2 on 2020-02-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200211_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(help_text='contact_phone_number', max_length=10),
        ),
    ]
