# Generated by Django 3.0.2 on 2020-02-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200211_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(help_text='contact_phone_number', max_length=10),
        ),
    ]
