# Generated by Django 3.0.2 on 2020-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200211_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='first_name', max_length=15)),
                ('last_name', models.CharField(help_text='last_name', max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/user/')),
                ('balance', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
