# Generated by Django 3.0.2 on 2020-02-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
