# Generated by Django 3.0.2 on 2020-02-12 05:02

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
